name: Autograding Tests
on:
  - push
  - workflow_dispatch
  - repository_dispatch
  - pull_request
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: PathExtractor
      # This is where you place your autograding tests
      # For more information on this runner, see the documentation at: https://github.com/classroom-resources/autograding-io-grader
      #
      # For example, you could run a test suite like this:
      # - name: Run tests
      #   uses: classroom-resources/autograding-io-grader@v1
      #     with:
      #       test-name: Addition Test
      #       id: addition-test
      #       command: "./bin/add.sh"
      #       input: 1 2
      #       expected-output: 3
      #       comparison-method: exact
      #       timeout: 10
    - name: Checkout reference code
      uses: actions/checkout@v4
      with:
        repository: UCR-CS182/RefPathExtractor
        path: RefPathExtractor
        token: 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
          
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r RefPathExtractor/requirements.txt
        pip install -r PathExtractor/requirements.txt

    - name: Run autograder
      id: run-test-phase1
      run: pytest RefPathExtractor/tests/test_phase1/ -q --tb=no --timeout=10
    
    # - name: Python test
    #   id: python-test
    #   uses: classroom-resources/autograding-python-grader@v1
    #   with:
    #     timeout: '15'
    #     max-score: '100'
    #     setup-command: 'pip install -r requirements.txt && cd ../'

    # - name: Autograding Reporter
    #   uses: classroom-resources/autograding-grading-reporter@v1
    #   # For more information on this runner, see the documentation at https://github.com/classroom-resources/autograding-grading-reporter
    #   # To output the results of the tests, you can use the
    #   # autograding-grading-reporter action like this:
    #   # env:
    #   # ADDITION-TEST_RESULTS: "${{ steps.addition - test.outputs.result }}"
    #   with:
    #     runners: run-test-phase1, run-test-phase2
    #     result-path: "results.xml"
